### ISSUE TITLE
Internationalisation doesn't work on the static content system

### ISSUE THREAD

**Issue by domingoruiz** [rocky-linux/rockylinux.org-hugo#146]
## Describe the bug
In the new static branch multilanguage does not work. The site starts up, and you can see the home page in all languages, but when you enter the post section, a 404 error appears in all languages ​​except English.

## To Reproduce
1. Hugo server
2. Choose any language other than English. 
3. Click on post.

**Comment by FoggyMtnDrifter** [comment]
This functionality is still a work in progress, we are just getting started with it, so this will be resolved before going to the `develop` branch. Thanks!

**Comment by domingoruiz** [comment]
[https://github.com/rocky-linux/rockylinux.org/pull/157](https://github.com/rocky-linux/rockylinux.org/pull/157)

**Comment by FoggyMtnDrifter** [comment]
Okay, so our current problem with implementing the blog section of the site is that if Hugo doesn't see a post targeted for a specific language, it won't generate the files for that language. This is a problem, because we don't currently plan on translating blog posts to other languages. If anyone has experience with a solution in which we could get Hugo to generate the files without needing to create language specific files or running scripts, we're all ears. The current plan if we can't find another solution is to append a language identifier to the end of the URL so that it forces the user onto the English version of the site. **Please keep in mind that we don't want to make anything difficult on the content creators, we just want them to be able to create a single markdown file and be done with it.**

**Comment by domingoruiz** [comment]
The solution consisting of add language identifier to the end of the URL is tested?

Thanks

**Comment by FoggyMtnDrifter** [comment]
Yes @domingoruiz I tested it on my end, it basically will force the site to be displayed in English, resulting in the successful display of the blog post. It's a bit simple, but wouldn't require any additional steps from content creators. We want to make sure it's as easy as possible to create content, no scripts, nothing other than adding the markdown files.

This is going to be a last resort option, though. If someone else can come up with a solution that still doesn't require the use of scripts or anything, we'd welcome their input.

**Comment by domingoruiz** [comment]
I think that this issue can be closed...

Thanks
