### ISSUE TITLE
Implement CSP

### ISSUE THREAD

**Issue by FoggyMtnDrifter** [rocky-linux/rockylinux.org-hugo#186]
**Is your feature request related to a problem? Please describe.**

It's been suggested to implement a content security policy on the site to protect against injections.

**Describe the solution you'd like**

While this rarely occurs on static sites, it wouldn't hurt to implement it.

**Comment by FoggyMtnDrifter** [comment]
Fixed with 660bd39d4296cea0e4d58bad2643edf5f49cb73a

**Comment by ghost** [comment]
Hi, thanks for implementing this change. However, what you implemented adds no security benefit at all.

"unsafe-inline" is effectively zero protection. You need to whitelist the resources the site uses and move any inline javascript to external files. I'll be happy to add a PR later, but not right now.

**Comment by FoggyMtnDrifter** [comment]
@remyabel As mentioned previously, we're using Hugo to generate values in the JavaScript, and Hugo templating cannot be used in JavaScript, unfortunately, meaning we'd need to hardcode the values, which won't be sustainable for various reasons.

While I appreciate the concern, the site doesn't really load any external resources (other than links), so this effectively shouldn't be a problem. I think this StackOverflow user explains it quite well: https://stackoverflow.com/a/44698400

We're happy to get your contributions towards improving the policy otherwise, though! Just keep in mind that the way we're generating the values into the JavaScript wouldn't be sustainable any other way. :))

**Comment by ghost** [comment]
> @remyabel As mentioned previously, we're using Hugo to generate values in the JavaScript, and Hugo templating cannot be used in JavaScript, unfortunately, meaning we'd need to hardcode the values, which won't be sustainable for various reasons.

What you did was hard-code it in the index.html file, but this [article](https://blog.jeremylikness.com/blog/create-content-security-policy-csp-in-hugo/) shows how you can generate it from Hugo. And a whitelist is going to involve hard-coding. It is a whitelist after all. I'm sure you can programmatically add to the whitelist but that's beyond the scope of this discussion.

> While I appreciate the concern, the site doesn't really load any external resources (other than links), so this effectively shouldn't be a problem. I think this StackOverflow user explains it quite well: https://stackoverflow.com/a/44698400

XSS is only one attack vector and not the only one. As I said earlier, static websites can still suffer from data injection attacks. This is exactly why I run NoScript in my browser, but in order for your site to actually be usable, users are going to enable JavaScript and that's why a content security policy is important. You're also forgetting about the dangers of an attack vector via CDN (however unlikely this is, this is why hashes and cross-origin policies are used which you are missing for alpinejs). Either way, it takes very little effort to implement for huge benefit.

**Comment by ghost** [comment]
On a side note, these are the [recommendations](https://docs.pagure.org/infra-docs/dev-guide/security_policy.html#security-headers) from the Fedora Infrastructure Application Security Policy. There's no harm in implementing these either.

**Comment by FoggyMtnDrifter** [comment]
> What you did was hard-code it in the index.html file, but this article shows how you can generate it from Hugo. And a whitelist is going to involve hard-coding. It is a whitelist after all. I'm sure you can programmatically add to the whitelist but that's beyond the scope of this discussion.

Are you referring to the header? I'm not talking about hard-coding the CSP values, I'm talking about hardcoding the JavaScript data generated by Hugo.

Feel free to open a PR later and link this issue. I'm not against a CSP, I just think you misunderstood what I was talking about in terms of the inline JavaScript.

**Comment by FoggyMtnDrifter** [comment]
A hash for the inline JavaScript would be sufficient in this case, I would think, though.

**Comment by FoggyMtnDrifter** [comment]
I realize I didn't come across quite clearly. Basically we have Hugo generating some of the data in the inline JavaScript. Due to this, every time someone adds a new language to our site, the data changes. This will prevent us from creating a hash for the inline JavaScript without updating it for every PR. Does that make sense?

We're using StaticDeploy to deploy the site, so maybe @hbjydev can see if there's a better way to handle it on that side of things.

**Comment by FoggyMtnDrifter** [comment]
Really the only valid option would be to use a nonce at this point.

**Comment by FoggyMtnDrifter** [comment]
Well, I started improving the header inline, but I think I've hit a roadblock. Alpine.JS requires eval to function, and would force us to use "unsafe-eval".

**Comment by FoggyMtnDrifter** [comment]
For reference: https://github.com/theNewDynamic/thenewdynamic.com/issues/110

**Comment by FoggyMtnDrifter** [comment]
From reading the issue linked in the aforementioned issue, it appears that they will implement measures in v3 to prevent issues with CSP, but for now we'll be forced to use 'unsafe-eval'.

**Comment by FoggyMtnDrifter** [comment]
I went ahead and implemented 3c8f3494848e32bebf3e20bb98471df4c42858dc. Let me know if you have any suggested improvements. I think as long as we're using the nonce it should be fine. At least, much safer from attacks than otherwise not having it implemented.

**Comment by ghost** [comment]
For the inline JavaScript a few approaches come to mind:

1. Enforce changing the hash whenever adding a new language. Sure this is annoying, but no different than enforcing i.e linting changes. Since the hash will no longer match it will be immediately obvious when it breaks
2. Automate/script it somehow
3. Use [Hugo Pipes](https://gohugo.io/hugo-pipes/js/) to process the JavaScript. I'm not familiar with Hugo but this looks the most relevant

As for nonce vs hash, a nonce has to be regenerated on every HTTP request, it can't just be hard-coded like here. So we need to use a hash anyway unless you decide to add server-side CSP support.

**Comment by hbjydev** [comment]
I'm sorry, but I fail to see why we would need CSP support in this project. @remyabel Can you enlighten me here? It's a completely static site with no backend, so there's no risk in terms of data unless the end user has installed a virus that hacks its host through JavaScript files in a specific browser, which for _everyone_ is extremely unlikely.

And plus, anything that we have to 'enforce' or do manually is strictly off the table. We're going to be using Weblate for our translations, so anything that requires us to manually add something prevents us from managing it in a sustainable way, which we desperately need to do given the scope of this and number of contributors.

If you can explain to me why we need CSP on a 100% static website, then I'll re-open this. But until then, I'm marking this as wontfix, because I fail to see why it's necessary.

**Comment by ghost** [comment]
It doesn't matter if it's a static website or not. It was already pointed out that alpinejs requires `unsafe-eval` which is an XSS vector. I also don't really consider the likelihood of a vulnerability to be that big of a factor. I lock my front door to keep people out no matter how unlikely it is that someone will break in.

Anyway, I understand that based on the reasoning you gave implementing this change will be painful so I'll concede.
